# Generated by Django 3.2.8 on 2021-11-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.CharField(max_length=2555)),
                ('product_Code', models.IntegerField(unique=True)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categor_id', models.IntegerField()),
                ('category', models.CharField(max_length=2555)),
            ],
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_boy_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phno', models.IntegerField()),
                ('place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='delivery_assigned',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('products', models.CharField(max_length=2555)),
                ('product_order_id', models.IntegerField(unique=True)),
                ('assigned', models.CharField(max_length=255)),
                ('place_to_deliver', models.CharField(max_length=255)),
                ('delivery_time_planned', models.DateField()),
                ('amount_recived', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('products', models.CharField(max_length=255)),
                ('product_Code', models.IntegerField(unique=True)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('address3', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=25)),
                ('pincode', models.IntegerField()),
                ('pmmode', models.CharField(max_length=255)),
                ('order_status', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phno', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.CharField(max_length=2555)),
                ('product_Code', models.IntegerField(unique=True)),
                ('price', models.IntegerField()),
                ('weight', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
