# Generated by Django 3.2.8 on 2021-11-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0002_cart_category_delivery_delivery_assigned_orders_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phno',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
