# Generated by Django 3.2.8 on 2021-12-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverAddresstable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('address3', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=25)),
                ('pincode', models.IntegerField()),
                ('pmmode', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('order_status', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phno', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
